export type InitialModalDataType = {
    mainColor: string;
    secondaryColor: string;
    categoryTitle: string;
    subCategories: {
        subcategoryTitle: string;
        items: ItemSkillType[];
    }[];
}[];

export type ItemSkillType = {
    skillId: string;
    text: string;
    value?: number;
    min: number;
    max: number;
    isChecked: boolean;
    categoryTitle?: string;
    subcategoryTitle?: string;
};
export const initialModalData: InitialModalDataType = [
    {
        mainColor: '#B4104C',
        secondaryColor: '#FFC0D7',
        categoryTitle: 'Стратегия и архитектура',
        subCategories: [
            {
                subcategoryTitle: 'Стратегическое планирование',
                items: [
                    {
                        skillId: '1',
                        text: 'Стратегическое планирование',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '2',
                        text: 'Координация информационных систем',
                        value: undefined,
                        min: 6,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '3',
                        text: 'Информационное управление',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '4',
                        text: 'Корпоративная и бизнес-архитектура',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '5',
                        text: 'Архитектура решений',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '6',
                        text: 'Инновации',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '7',
                        text: 'Мониторинг новейших технологий',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '8',
                        text: 'Исследование',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '81',
                        text: 'Управление спросом',
                        value: undefined,
                        min: 5,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '82',
                        text: 'Оценка инвестиций',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '83',
                        text: 'Управление финансами',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '84',
                        text: 'Измерение',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '85',
                        text: 'Устойчивое развитие',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '86',
                        text: 'Управление непрерывностью',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Безопасность и конфиденциальность',
                items: [
                    {
                        skillId: '9',
                        text: 'Информационная безопасность',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '10',
                        text: 'Информационное обеспечение',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '11',
                        text: 'Защита персональных данных',
                        value: undefined,
                        min: 5,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '12',
                        text: 'Изучение уязвимости',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '13',
                        text: 'Анализ угроз',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление, риск и соблюдение требований',
                items: [
                    {
                        skillId: '14',
                        text: 'Управление ИТ',
                        value: undefined,
                        min: 6,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '15',
                        text: 'Управление рисками',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '16',
                        text: 'Аудит',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '17',
                        text: 'Управление качеством',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '171',
                        text: 'Обеспечение качества',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Консультации и рекомендации',
                items: [
                    {
                        skillId: '133',
                        text: 'Консалтинг',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '132',
                        text: 'Консультация специалиста',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '131',
                        text: 'Методы и инструменты',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#7208A8',
        secondaryColor: '#EDCAFF',
        categoryTitle: 'Изменения и трансформация',
        subCategories: [
            {
                subcategoryTitle: 'Внедрение изменений',
                items: [
                    {
                        skillId: '51',
                        text: 'Управление портфелем',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '52',
                        text: 'Управление программами',
                        value: undefined,
                        min: 6,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '53',
                        text: 'Управление проектами',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '53',
                        text: 'Сопровождение программ и проектов',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Анализ изменений',
                items: [
                    {
                        skillId: '54',
                        text: 'Анализ бизнес-ситуации',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '55',
                        text: 'Оценка целесообразности',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '561',
                        text: 'Определение и управление требо-ми',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '56',
                        text: 'Бизнес-моделирование',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '57',
                        text: 'Приемочные испытания',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Планирование изменений',
                items: [
                    {
                        skillId: '58',
                        text: 'Улучшение бизнес - процессов',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '59',
                        text: 'Развитие организационных возможностей',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '60',
                        text: 'Разработка организационной структуры',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '61',
                        text: 'Управление органи-ми изменениями',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '62',
                        text: 'Управление выгодами',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },

    {
        mainColor: '#BF9501',
        secondaryColor: '#FFF1C0',
        categoryTitle: 'Разработка и внедрение',
        subCategories: [
            {
                subcategoryTitle: 'Разработка систем',
                items: [
                    {
                        skillId: '18',
                        text: 'Управление продуктами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '181',
                        text: 'Управление разработкой систем',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '182',
                        text: 'Про-ние жизненного цикла систем и ПО',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '19',
                        text: 'Проектирование систем',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '19123',
                        text: 'Проектирование ПО',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '191',
                        text: 'Проектирование сети',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '20',
                        text: 'Про-ние аппаратного обеспечения',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '201',
                        text: 'Программирование/разработка ПО',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '202',
                        text: 'Интеграция и сборка систем',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '203',
                        text: 'Тестирование',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '204',
                        text: 'Конфигурация ПО',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '205',
                        text: 'Техника безопасности',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '206',
                        text: 'Оценка безопасности',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '207',
                        text: 'Радиочастотная техника',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '208',
                        text: 'Разработка анимации',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Данные и аналитика',
                items: [
                    {
                        skillId: '21',
                        text: 'Управление данными',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '22',
                        text: 'Моделирование и проектирование данных',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '23',
                        text: 'Проектирование базы данных',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '24',
                        text: 'Инжиниринг данных',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '25',
                        text: 'Администрирование базы данных',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '26',
                        text: 'Дата сайенс',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '261',
                        text: 'Машинное обучение',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '262',
                        text: 'Бизнес-аналитика',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '263',
                        text: 'Визуализация данных',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Опыт пользователя',
                items: [
                    {
                        skillId: '264',
                        text: 'Исследование пользователей',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '265',
                        text: 'Анализ пользовательского опыта',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '266',
                        text: 'Прое-ние пользовательского опыта',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '267',
                        text: 'Оценка пользовательского опыта',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление контентом',
                items: [
                    {
                        skillId: '27',
                        text: 'Создание контентаи',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '28',
                        text: 'Публикация контента',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '29',
                        text: 'Управление знаниями',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Вычислительные науки',
                items: [
                    {
                        skillId: '271',
                        text: 'Научная модель',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '282',
                        text: 'Числовой анализ',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '293',
                        text: 'Высокопроизводительные вычисления',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#138D0A',
        secondaryColor: '#CEFFCA',
        categoryTitle: 'Взаимоотношения и взаимодействия',
        subCategories: [
            {
                subcategoryTitle:
                    'Управление отношениями с заинтересованными сторонами',
                items: [
                    {
                        skillId: '30',
                        text: 'Сорсинг',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '31',
                        text: 'Управление поставщиками',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '32',
                        text: 'Управление контрактами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '33',
                        text: 'Управление взаимоотношениями',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '34',
                        text: 'Служба поддержки клиентов',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '35',
                        text: 'Бизнес администрирование',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Анализ изменений',
                items: [
                    {
                        skillId: '36',
                        text: 'Маркетинг',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },

                    {
                        skillId: '37',
                        text: 'Продажи',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },

                    {
                        skillId: '38',
                        text: 'Поддержка продаж',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#FC8616',
        secondaryColor: '#FFE9D4',
        categoryTitle: 'Доставка и эксплуатация',
        subCategories: [
            {
                subcategoryTitle: 'Технологический менеджмент',
                items: [
                    {
                        skillId: '39',
                        text: 'Управление технологическими услугами',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '40',
                        text: 'Поддержка приложения',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '41',
                        text: 'Инфраструктура ИТ',
                        value: undefined,
                        min: 1,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '42',
                        text: 'Системное программное обеспечение',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '421',
                        text: 'Поддержка сети',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '422',
                        text: 'Установка и удаление систем',
                        value: undefined,
                        min: 1,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '423',
                        text: 'Управление конфигурациями',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '424',
                        text: 'Релиз и развертывание',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '425',
                        text: 'Управление хранением',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '426',
                        text: 'Управление объектами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление услугами',
                items: [
                    {
                        skillId: '431',
                        text: 'Управление уровнем услуг',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '43',
                        text: 'Управление каталогом услуг',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '45',
                        text: 'Управление доступностью',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '46',
                        text: 'Управление мощностями',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '441',
                        text: 'Управление инцидентами',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '442',
                        text: 'Управление проблемами',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '443',
                        text: 'Контроль изменений',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '444',
                        text: 'Управление активами',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '445',
                        text: 'Принятие услуг',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Услуги по обеспечению безопасности',
                items: [
                    {
                        skillId: '47',
                        text: 'Операции по обеспечению безопасности',
                        value: undefined,
                        min: 1,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '48',
                        text: 'Оценка уязвимости',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '49',
                        text: 'Цифровая криминалистика',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '50',
                        text: 'Тестирование на проникновение',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#0E72AB',
        secondaryColor: '#C8EBFF',
        categoryTitle: 'Люди и навыки',
        subCategories: [
            {
                subcategoryTitle: 'Управление людскими ресурсамии',
                items: [
                    {
                        skillId: '63',
                        text: 'Управление производительностью',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '64',
                        text: 'Впечатление персонала',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '65',
                        text: 'Организационная фасилитация',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '66',
                        text: 'Профессиональное развитие',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '67',
                        text: 'Планирование трудовых ресурсов',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '68',
                        text: 'Обеспечение ресурсами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление навыками',
                items: [
                    {
                        skillId: '69',
                        text: 'Управление обучением и развитием',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '70',
                        text: 'Разработка и развитие обучения',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '71',
                        text: 'Проведение учебных мероприятий',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        skillId: '72',
                        text: 'Оценка компетенций',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '73',
                        text: 'Работа системы сертификации',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        skillId: '74',
                        text: 'Обучение',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        skillId: '75',
                        text: 'Формирование темы',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
];
