export type InitialModalDataType = {
    mainColor: string;
    secondaryColor: string;
    categoryTitle: string;
    subCategories: {
        subcategoryTitle: string;
        items: ItemSkillType[];
    }[];
}[];

export type ItemSkillType = {
    id: number;
    code: string;
    text: string;
    value?: number;
    min: number;
    max: number;
    isChecked: boolean;
    categoryTitle?: string;
    subcategoryTitle?: string;
};
export const initialModalData: InitialModalDataType = [
    {
        mainColor: '#B4104C',
        secondaryColor: '#FFC0D7',
        categoryTitle: 'Стратегия и архитектура',
        subCategories: [
            {
                subcategoryTitle: 'Стратегическое планирование',
                items: [
                    {
                        id: 1,
                        code: 'ITSP',
                        text: 'Стратегическое планирование',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 2,
                        code: 'ISCO',
                        text: 'Координация информационных систем',
                        value: undefined,
                        min: 6,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 3,
                        code: 'IRMG',
                        text: 'Информационное управление',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 4,
                        code: 'STPL',
                        text: 'Корпоративная и бизнес-архитектура',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 5,
                        code: 'ARCH',
                        text: 'Архитектура решений',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 6,
                        code: 'INOV',
                        text: 'Инновации',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 7,
                        code: 'EMRG',
                        text: 'Мониторинг новейших технологий',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 8,
                        code: 'RSCH',
                        text: 'Исследование',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 81,
                        code: 'DEMM',
                        text: 'Управление спросом',
                        value: undefined,
                        min: 5,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 82,
                        code: 'INVA',
                        text: 'Оценка инвестиций',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 83,
                        code: 'FMIT',
                        text: 'Управление финансами',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 84,
                        code: 'MEAS',
                        text: 'Измерение',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 85,
                        code: 'SUST',
                        text: 'Устойчивое развитие',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 86,
                        code: 'COPL',
                        text: 'Управление непрерывностью',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Безопасность и конфиденциальность',
                items: [
                    {
                        id: 9,
                        code: 'SCTY',
                        text: 'Информационная безопасность',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 10,
                        code: 'INAS',
                        text: 'Информационное обеспечение',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 11,
                        code: 'PEDP',
                        text: 'Защита персональных данных',
                        value: undefined,
                        min: 5,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 12,
                        code: 'VURE',
                        text: 'Изучение уязвимости',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 13,
                        code: 'THIN',
                        text: 'Анализ угроз',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление, риск и соблюдение требований',
                items: [
                    {
                        id: 14,
                        code: 'GOVN',
                        text: 'Управление ИТ',
                        value: undefined,
                        min: 6,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 15,
                        code: 'BURM',
                        text: 'Управление рисками',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 16,
                        code: 'AUDT',
                        text: 'Аудит',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 17,
                        code: 'QUMG',
                        text: 'Управление качеством',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 171,
                        code: 'QUAS',
                        text: 'Обеспечение качества',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Консультации и рекомендации',
                items: [
                    {
                        id: 133,
                        code: 'CNSL',
                        text: 'Консалтинг',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 132,
                        code: 'TECH',
                        text: 'Консультация специалиста',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 131,
                        code: 'METL',
                        text: 'Методы и инструменты',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#7208A8',
        secondaryColor: '#EDCAFF',
        categoryTitle: 'Изменения и трансформация',
        subCategories: [
            {
                subcategoryTitle: 'Внедрение изменений',
                items: [
                    {
                        id: 51,
                        code: 'POMG',
                        text: 'Управление портфелем',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 52,
                        code: 'PGMG',
                        text: 'Управление программами',
                        value: undefined,
                        min: 6,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 53,
                        code: 'PRMG',
                        text: 'Управление проектами',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 53,
                        code: 'PROF',
                        text: 'Сопровождение программ и проектов',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Анализ изменений',
                items: [
                    {
                        id: 54,
                        code: 'BUSA',
                        text: 'Анализ бизнес-ситуации',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 55,
                        code: 'FEAS',
                        text: 'Оценка целесообразности',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 561,
                        code: 'REQM',
                        text: 'Определение и управление требо-ми',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 56,
                        code: 'BSMO',
                        text: 'Бизнес-моделирование',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 57,
                        code: 'BPTS',
                        text: 'Приемочные испытания',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Планирование изменений',
                items: [
                    {
                        id: 58,
                        code: 'BPRE',
                        text: 'Улучшение бизнес - процессов',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 59,
                        code: 'OCDV',
                        text: 'Развитие организационных возможностей',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 60,
                        code: 'ORDI',
                        text: 'Разработка организационной структуры',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 61,
                        code: 'CIPM',
                        text: 'Управление органи-ми изменениями',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 62,
                        code: 'BENM',
                        text: 'Управление выгодами',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },

    {
        mainColor: '#BF9501',
        secondaryColor: '#FFF1C0',
        categoryTitle: 'Разработка и внедрение',
        subCategories: [
            {
                subcategoryTitle: 'Разработка систем',
                items: [
                    {
                        id: 18,
                        code: 'PROD',
                        text: 'Управление продуктами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 181,
                        code: 'DLMG',
                        text: 'Управление разработкой систем',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 182,
                        code: 'SLEN',
                        text: 'Про-ние жизненного цикла систем и ПО',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 19,
                        code: 'DESN',
                        text: 'Проектирование систем',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 19123,
                        code: 'SWDN',
                        text: 'Проектирование ПО',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 191,
                        code: 'NTDS',
                        text: 'Проектирование сети',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 20,
                        code: 'HWDE',
                        text: 'Про-ние аппаратного обеспечения',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 201,
                        code: 'PROG',
                        text: 'Программирование/разработка ПО',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 202,
                        code: 'SINT',
                        text: 'Интеграция и сборка систем',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 203,
                        code: 'TEST',
                        text: 'Тестирование',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 204,
                        code: 'PORT',
                        text: 'Конфигурация ПО',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 204444,
                        code: 'RESD',
                        text: 'Cистемы реального времени',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },

                    {
                        id: 205,
                        code: 'SFEN',
                        text: 'Техника безопасности',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 206,
                        code: 'SFAS',
                        text: 'Оценка безопасности',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 207,
                        code: 'RFEN',
                        text: 'Радиочастотная техника',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 208,
                        code: 'ADEV',
                        text: 'Разработка анимации',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Данные и аналитика',
                items: [
                    {
                        id: 21,
                        code: 'DATM',
                        text: 'Управление данными',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 22,
                        code: 'DTAN',
                        text: 'Моделирование и проектирование данных',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 23,
                        code: 'DBDS',
                        text: 'Проектирование базы данных',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 24,
                        code: 'DENG',
                        text: 'Инжиниринг данных',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 25,
                        code: 'DBAD',
                        text: 'Администрирование базы данных',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 26,
                        code: 'DATS',
                        text: 'Дата сайенс',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 261,
                        code: 'MLNG',
                        text: 'Машинное обучение',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 262,
                        code: 'BINT',
                        text: 'Бизнес-аналитика',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 263,
                        code: 'VISL',
                        text: 'Визуализация данных',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Опыт пользователя',
                items: [
                    {
                        id: 264,
                        code: 'URCH',
                        text: 'Исследование пользователей',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 265,
                        code: 'UNAN',
                        text: 'Анализ пользовательского опыта',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 266,
                        code: 'HCEV',
                        text: 'Прое-ние пользовательского опыта',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 267,
                        code: 'USEV',
                        text: 'Оценка пользовательского опыта',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление контентом',
                items: [
                    {
                        id: 27,
                        code: 'INCA',
                        text: 'Создание контентаи',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 28,
                        code: 'ICPM',
                        text: 'Публикация контента',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 29,
                        code: 'KNOW',
                        text: 'Управление знаниями',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Вычислительные науки',
                items: [
                    {
                        id: 271,
                        code: 'SCMO',
                        text: 'Научная модель',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 282,
                        code: 'NUAN',
                        text: 'Числовой анализ',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 293,
                        code: 'HPCC',
                        text: 'Высокопроизводительные вычисления',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#138D0A',
        secondaryColor: '#CEFFCA',
        categoryTitle: 'Взаимоотношения и взаимодействия',
        subCategories: [
            {
                subcategoryTitle:
                    'Управление отношениями с заинтересованными сторонами',
                items: [
                    {
                        id: 30,
                        code: 'SORC',
                        text: 'Сорсинг',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 31,
                        code: 'SUPP',
                        text: 'Управление поставщиками',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 32,
                        code: 'ITCM',
                        text: 'Управление контрактами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 33,
                        code: 'RLMT',
                        text: 'Управление взаимоотношениями',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 34,
                        code: 'CSMG',
                        text: 'Служба поддержки клиентов',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 35,
                        code: 'ADMN',
                        text: 'Бизнес администрирование',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Анализ изменений',
                items: [
                    {
                        id: 36,
                        code: 'MKTG',
                        text: 'Маркетинг',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },

                    {
                        id: 37,
                        code: 'SALE',
                        text: 'Продажи',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },

                    {
                        id: 38,
                        code: 'SSUP',
                        text: 'Поддержка продаж',
                        value: undefined,
                        min: 1,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#FC8616',
        secondaryColor: '#FFE9D4',
        categoryTitle: 'Доставка и эксплуатация',
        subCategories: [
            {
                subcategoryTitle: 'Технологический менеджмент',
                items: [
                    {
                        id: 39,
                        code: 'ITMG',
                        text: 'Управление технологическими услугами',
                        value: undefined,
                        min: 5,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 40,
                        code: 'ASUP',
                        text: 'Поддержка приложения',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 41,
                        code: 'ITOP',
                        text: 'Инфраструктура ИТ',
                        value: undefined,
                        min: 1,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 42,
                        code: 'SYSP',
                        text: 'Системное программное обеспечение',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 421,
                        code: 'NTAS',
                        text: 'Поддержка сети',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 422,
                        code: 'HSIN',
                        text: 'Установка и удаление систем',
                        value: undefined,
                        min: 1,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 423,
                        code: 'CFMG',
                        text: 'Управление конфигурациями',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 424,
                        code: 'RELM',
                        text: 'Релиз и развертывание',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 425,
                        code: 'STMG',
                        text: 'Управление хранением',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 426,
                        code: 'DCMA',
                        text: 'Управление объектами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление услугами',
                items: [
                    {
                        id: 431,
                        code: 'SLMO',
                        text: 'Управление уровнем услуг',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 43,
                        code: 'SCMG',
                        text: 'Управление каталогом услуг',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 45,
                        code: 'AVMT',
                        text: 'Управление доступностью',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 46,
                        code: 'CPMG',
                        text: 'Управление мощностями',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 441,
                        code: 'USUP',
                        text: 'Управление инцидентами',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 442,
                        code: 'PBMG',
                        text: 'Управление проблемами',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 443,
                        code: 'CHMG',
                        text: 'Контроль изменений',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 444,
                        code: 'ASMG',
                        text: 'Управление активами',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 445,
                        code: 'SEAC',
                        text: 'Принятие услуг',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Услуги по обеспечению безопасности',
                items: [
                    {
                        id: 47,
                        code: 'SCAD',
                        text: 'Операции по обеспечению безопасности',
                        value: undefined,
                        min: 1,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 48,
                        code: 'VUAS',
                        text: 'Оценка уязвимости',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 49,
                        code: 'DGFS',
                        text: 'Цифровая криминалистика',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 50,
                        code: 'PENT',
                        text: 'Тестирование на проникновение',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
    {
        mainColor: '#0E72AB',
        secondaryColor: '#C8EBFF',
        categoryTitle: 'Люди и навыки',
        subCategories: [
            {
                subcategoryTitle: 'Управление людскими ресурсамии',
                items: [
                    {
                        id: 63,
                        code: 'PEMT',
                        text: 'Управление производительностью',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 64,
                        code: 'EEXP',
                        text: 'Впечатление персонала',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 65,
                        code: 'OFCL',
                        text: 'Организационная фасилитация',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 66,
                        code: 'PDSV',
                        text: 'Профессиональное развитие',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 67,
                        code: 'WFPL',
                        text: 'Планирование трудовых ресурсов',
                        value: undefined,
                        min: 4,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 68,
                        code: 'RESC',
                        text: 'Обеспечение ресурсами',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                ],
            },
            {
                subcategoryTitle: 'Управление навыками',
                items: [
                    {
                        id: 69,
                        code: 'ETMG',
                        text: 'Управление обучением и развитием',
                        value: undefined,
                        min: 3,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 70,
                        code: 'TMCR',
                        text: 'Разработка и развитие обучения',
                        value: undefined,
                        min: 3,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 71,
                        code: 'ETDL',
                        text: 'Проведение учебных мероприятий',
                        value: undefined,
                        min: 2,
                        max: 5,
                        isChecked: false,
                    },
                    {
                        id: 72,
                        code: 'LEDA',
                        text: 'Оценка компетенций',
                        value: undefined,
                        min: 3,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 73,
                        code: 'CSOP',
                        text: 'Работа системы сертификации',
                        value: undefined,
                        min: 2,
                        max: 6,
                        isChecked: false,
                    },
                    {
                        id: 74,
                        code: 'TEAC',
                        text: 'Обучение',
                        value: undefined,
                        min: 2,
                        max: 7,
                        isChecked: false,
                    },
                    {
                        id: 75,
                        code: 'SUBF',
                        text: 'Формирование темы',
                        value: undefined,
                        min: 4,
                        max: 7,
                        isChecked: false,
                    },
                ],
            },
        ],
    },
];
